checks:
  php: true

filter:
  excluded_paths:
    - "vendor/*"
    - "migrations/*"

build:
  nodes:
    analysis:
      dependencies:
        override:
          - composer self-update --2
          - composer install --no-interaction --prefer-dist --no-progress
      tests:
        override:
          - php-scrutinizer-run
          - vendor/bin/phpcs --standard=phpcs.xml src tests
